config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end
  
  def new
    @tweet = Tweet.new
  end
  
  def create
    @tweet = Tweet.new(message: params[:tweet][:message], tdate: Time.current)
    if @tweet.save
      flash[:notice] = '1レコード追加しました'
      redirect_to '/'
    else
      render 'new'
    end
  end
  
  def show
    @tweet = Tweet.find(params[:id])
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    flash[:notice] = '1レコード削除しました'
    redirect_to'/'
  end
  
  def edit
    @tweet = Tweet.find(params[:id])
  end
  
  def update
    @tweet = Tweet.find(params[:id])
    @tweet.message = params[:tweet][:message]
    if @tweet.save
      flash[:notice] = '1レコード更新しました'
      redirect_to '/'
    else
      render'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    
  </head>

 <body>
    <div id="container">
      <div id="header">
        <%= render "header" %>
      </div>

      <div id="sidebar">
        <%= render "sidebar" %>
      </div>
      
      <div id="content">
        <%= yield %>
      </div>
      
      <div id="footer">
        <%= render "footer" %>
      </div>
    </div>
  </body>
</html>

app/views/tweets/_header.html.erb
<head>
<img src="a.ping" title="近畿大学">

</head>

<body>
    ツイート
    フォロー
    フォロワー
    いいね
    
    
</body>

app/views/tweets/_sidebar.html.erb
<h1>
    近代太郎
</h1>

<body>
    近畿大学総務部広報室のTwitter公式アカウントです。近畿大学ホームページの更新
    情報を発信していきます。個別のお問い合わせには返信を行っておりませんので
    、ご了承ください。
    
    
    <p>
        大阪府東大阪市
    </p>
    <p>
        instagram.com/kindaigakupr/
    </p>
    <p>
        2010年12月に登録
    </p>
    
    
</body>

app/views/tweets/edit.html.erb
<span style="color: red;">
<% if @tweet.errors.present? %>
	<h3>エラーがあります</h3>
	<ul>
		<% @tweet.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>
</span>


<%= form_for @tweet , url: {action: :update} do |f| %>
	<%= f.label :message, 'つぶやき : ' %>
	<%= f.text_field :message %>
	<%= f.submit 'つぶやく' %>
<% end %>

app/views/tweets/index.html.erb
<span style="color: green;">
	<% if flash[:notice] %>
	<%= flash[:notice] %>
	<% end %>
</span>

<table>
	<% @tweets.each do |t| %>
	<tr>
		<td><%= t.message %></td>
		<td><%= ((Time.current - t.tdate) / 60).to_i.to_s %>分前</td>
		<td>
			<%= link_to '表示', tweet_path(t.id) %>
			<%= link_to '削除', tweet_path(t.id), method: :delete %>
			<%= link_to '編集', edit_tweet_path(t.id) %>
		</td>
	</tr>
	<% end %>
</table>

<%= link_to 'つぶやく', new_tweet_path %>

app/views/tweets/new.html.erb
<span style="color: red;">
<% if @tweet.errors.present? %>
	<h3>エラーがあります</h3>
	<ul>
		<% @tweet.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>
</span>


<%= form_for @tweet , url: {action: :create} do |f| %>
	<%= f.label :message, 'つぶやき : ' %>
	<%= f.text_field :message %>
	<%= f.submit 'つぶやく' %>
<% end %>

app/views/tweets/show.html.erb
<table>
    <tr>
        <td><%= @tweet.message %></td>
        <td><%= @tweet.tdate %></td>
    </tr>
</table>

<%= link_to '戻る', :back %>